name = "feedback"
main = "workers/feedback.js"
compatibility_date = "2024-01-01"

# KV Namespaces for storing feedback and stroke data
[[kv_namespaces]]
binding = "SOFA_TAGS"
id = "4732a4548a064b9b90e2f41eda556fc6"
preview_id = "82e4b9df98264eac84a823ec541334ac"

# R2 Bucket for storing reference images (optional, for future use)
[[r2_buckets]]
binding = "SOFA_REFERENCE"
bucket_name = "sofa-reference"

