name = "draw-bot"
account_id = "665aca072a7cddbc216be6b25a6fd951"
main = "workers/draw-bot.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "SOFA_TAGS"
id = "4732a4548a064b9b90e2f41eda556fc6"
preview_id = "82e4b9df98264eac84a823ec541334ac"

